---
- name: installing and launching metrics
  hosts: webservers
  become: yes
  tasks:
 
# Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/metric.config
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: enable and configure Docker module
    command: metricbeat modules enable system

    # Use command module
  - name: setup metricbeat
    command: metricbeat setup

    # Use comand comdule
  - name: start metricbeat
    command: service metricbeat start
